### PR TITLE
fix: allow localhost and svg namespace urls

### PR DESCRIPTION
**Pull request by jason-ha**
#7

### CODE REVIEW

**Comment by A-Katopodis** [comment]
Hi @jason-ha  we resolved this with the new release of v0.1.7. I didn't merge the PR as I wanted to add unit tests but the changes have been made.

Thanks for your contribution!

**Comment by A-Katopodis** [comment]
Closed PR as the functionality it tried to provide was added

**Comment by jason-ha** [comment]
@A-Katopodis, can you re-open and merge? Main branch doesn't appear to handle svg namespace, unless I am reading the code incorrectly. (I just looked to see if main branch had the same changes and it does not.)

**Comment by A-Katopodis** [comment]
@jason-ha the new changes actually include the full exclusion of the xlmns attribute. What you want is the exclusion of the svg namespace regardless of where is present? Because from my understanding it should only exist in the xlmns attribute

**Comment by jason-ha** [comment]
@A-Katopodis, I see it now. Added in a prior change. The comment saying:
  TODO: add more typical false positives such as XML schemas after more testing
should be updated.

**Pull request closed without merging**
